### ISSUE TITLE
可否api实现对照翻译？

### ISSUE THREAD

**Issue by rain-xray** [Menghuan1918/pdfdeal#1]
如题，使用api实现pdf文件上传与翻译html格式下载？

**Comment by Menghuan1918** [comment]
已经提交了：https://github.com/Menghuan1918/pdfdeal/commit/3f3fdb06c956bceb5655cda7f2ba65381fe6115b

使用参见https://github.com/Menghuan1918/pdfdeal/blob/main/docs/doc2x_cn.md#%E8%8E%B7%E5%BE%97doc2x%E7%9A%84%E7%BF%BB%E8%AF%91%E5%86%85%E5%AE%B9

**Comment by rain-xray** [comment]
> 已经提交了：[3f3fdb0](https://github.com/Menghuan1918/pdfdeal/commit/3f3fdb06c956bceb5655cda7f2ba65381fe6115b)
> 
> 使用参见https://github.com/Menghuan1918/pdfdeal/blob/main/docs/doc2x_cn.md#%E8%8E%B7%E5%BE%97doc2x%E7%9A%84%E7%BF%BB%E8%AF%91%E5%86%85%E5%AE%B9

太速度了，万分感谢！
