### ISSUE TITLE
dify集成

### ISSUE THREAD

**Issue by kenneth-bro** [Menghuan1918/pdfdeal#15]
您好.这个如何和dify集成.源代码改造吗？

**Comment by Menghuan1918** [comment]
目前暂时只能自己手动处理了文件后再传...

不过下个版本应该会做，通过dify的API自动上传到知识库里

**Comment by Menghuan1918** [comment]
https://menghuan1918.github.io/pdfdeal-docs/zh/demo/RAG_pre.html

抱歉API对接要花费的时间还是太多了，就没去做...暂时还是手动进行预处理后手动上传吧，我测试下来预处理后可以显著提升召回效果

**Comment by kenneth-bro** [comment]
> https://menghuan1918.github.io/pdfdeal-docs/zh/demo/RAG_pre.html
> 
> 抱歉API对接要花费的时间还是太多了，就没去做...暂时还是手动进行预处理后手动上传吧，我测试下来预处理后可以显著提升召回效果

👍
