### ISSUE TITLE
支持异步吗？

### ISSUE THREAD

**Issue by chung1912** [Menghuan1918/pdfdeal#28]
支持异步吗？

**Comment by Menghuan1918** [comment]
可以用`from pdfdeal.Doc2X.Convert import *`导入异步的函数用哒

这两天我写下使用文档吧~

**Comment by Menghuan1918** [comment]
这是异步的使用文档
https://menghuan1918.github.io/pdfdeal-docs/zh/guide/Doc2X/async.html
