### ISSUE TITLE
图像渲染失败

### ISSUE THREAD

**Issue by Upcreat** [Menghuan1918/pdfdeal#34]
大佬您好，麻烦问一下，使用您这个框架在fastgpt进行知识库问答的时候发现图像渲染不出来，您遇到过吗。
![局部截取_20240829_103957](https://github.com/user-attachments/assets/db2ce153-ac2b-4ac8-868f-03bc282df6a8)

**Comment by Menghuan1918** [comment]
因为默认转换下来是链接到本地的图片吧，格式类似于`![图片](./本地路径/图片.png)`

得自己手动上传到CDN上去才行

https://menghuan1918.github.io/pdfdeal-docs/zh/demo/RAG_pre.html#step3-%E8%BD%AC%E6%8D%A2%E5%9B%BE%E7%89%87%E4%B8%BA%E5%9C%A8%E7%BA%BFurl

**Comment by Upcreat** [comment]
按照教程，手动上传到阿里云的oss上面了，不知道是不是模型没理解问答的内容还是提示词没写好。大佬方便分享一下您的提示词吗

**Comment by Menghuan1918** [comment]
那应该是大模型把`![](<网址>)`里面的'<''和>'忽略了，你可以试试：

`需要引用图片时使用严格markdown规格，即![名字](<网址>)的形式回答`

**Comment by Upcreat** [comment]
ok ,我试试
