### ISSUE TITLE
上传图片可以放入通过自动创建的文件夹（以文件名命名）内吗

### ISSUE THREAD

**Issue by Huxb12138** [Menghuan1918/pdfdeal#53]
这样可以方便在对象存储服务中管理图片

**Comment by Huxb12138** [comment]
![image](https://github.com/user-attachments/assets/bd22d4e4-cfeb-427b-97c7-ad930c6158cf)
上次PR之前自己弄了一版是这样的效果，每次对单个MD文件上传时，创建以MD名称命名的文件夹并整合起来。

**Comment by Menghuan1918** [comment]
> ![image](https://private-user-images.githubusercontent.com/91454703/387533223-bd22d4e4-cfeb-427b-97c7-ad930c6158cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDQ5MDIsIm5iZiI6MTczMjAwNDYwMiwicGF0aCI6Ii85MTQ1NDcwMy8zODc1MzMyMjMtYmQyMmQ0ZTQtY2ZlYi00MjdiLTk3YzctYWQ5MzBjNjE1OGNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA4MjMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMDgzZjJmZWQ4ZTFlZTgxNDYxOTQ1ZWMzYmVjZjhlNzJhZTg0NzMwNGM1ZDNjODIyOTBkNzYyYWU4MDM1NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vinG5Yb-gHfv4dqP6mWxtnvDKL4Xf1R31qsrZLGu0Vs) 上次PR之前自己弄了一版是这样的效果，每次对单个MD文件上传时，创建以MD名称命名的文件夹并整合起来。

的确，这样也可以，我后面改一下

**Comment by Menghuan1918** [comment]
https://github.com/Menghuan1918/pdfdeal/releases/tag/v0.4.10
