### ISSUE TITLE
$$格式如何支持

### ISSUE THREAD

**Issue by lizhuang2511** [Menghuan1918/pdfdeal#57]

**Comment by Menghuan1918** [comment]
$$格式？支持什么

是指的导出markdown的公式类型吗

**Comment by lizhuang2511** [comment]
是的

**Comment by Menghuan1918** [comment]
> 是的

https://menghuan1918.github.io/pdfdeal-docs/zh/guide/pdf.html

output_format指定为"md_dollar"就是以$$形式导出了
